//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telecom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipment()
        {
            this.Ports = new HashSet<Ports>();
        }
    
        public int ID { get; set; }
        public string SerialNumber { get; set; }
        public int IDTypeEquipment { get; set; }
        public int InventoryNumberOS { get; set; }
        public Nullable<int> IDEmployee { get; set; }
        public int IDSubscriber { get; set; }
        public Nullable<System.DateTime> DateInstall { get; set; }
        public bool Active { get; set; }
        public string Note { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Subscribers Subscribers { get; set; }
        public virtual TypesEquipment TypesEquipment { get; set; }
        public virtual OS OS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ports> Ports { get; set; }
    }
}
