//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telecom
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Citys> Citys { get; set; }
        public virtual DbSet<Districts> Districts { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<LocationAddresses> LocationAddresses { get; set; }
        public virtual DbSet<Modules> Modules { get; set; }
        public virtual DbSet<OS> OS { get; set; }
        public virtual DbSet<Ports> Ports { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Streets> Streets { get; set; }
        public virtual DbSet<Subscribers> Subscribers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypesBuilding> TypesBuilding { get; set; }
        public virtual DbSet<TypesEquipment> TypesEquipment { get; set; }
        public virtual DbSet<TypesModules> TypesModules { get; set; }
        public virtual DbSet<TypesPorts> TypesPorts { get; set; }
    }
}
