//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telecom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modules
    {
        public int ID { get; set; }
        public int IDModule { get; set; }
        public int IDRole { get; set; }
    
        public virtual TypesModules TypesModules { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
