//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telecom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ports
    {
        public int ID { get; set; }
        public int IDTypePorts { get; set; }
        public int IDEquipment { get; set; }
        public string IPaddress { get; set; }
        public string MACaddress { get; set; }
        public int CountPorts { get; set; }
    
        public virtual Equipment Equipment { get; set; }
        public virtual TypesPorts TypesPorts { get; set; }
    }
}
