//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Telecom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscribers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subscribers()
        {
            this.Equipment = new HashSet<Equipment>();
        }
    
        public int ID { get; set; }
        public string Number { get; set; }
        public string SecondName { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public int IDGender { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string RegistrationAddress { get; set; }
        public string IDLocationAddress { get; set; }
        public string SerialPasport { get; set; }
        public string NumberPasport { get; set; }
        public string DivisionCode { get; set; }
        public string IssuedBy { get; set; }
        public System.DateTime DateIssue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipment> Equipment { get; set; }
        public virtual Genders Genders { get; set; }
        public virtual LocationAddresses LocationAddresses { get; set; }
    }
}
